context("Test confirm_libraries")

test_that("confirm_libraries message for mising libraries", {
  curdir  = getwd()
  tmpfile <- tempfile()
  dir.create(tmpfile)
  file.copy(file.path(curdir,"with_libraries.R"), file.path(tmpfile, "with_libraries.R"))
  setwd(tmpfile)
  expect_output(confirm_libraries(),'Following libraries are not installed:\nDO_NOT_EXISTS' )
  setwd(curdir)
})

test_that("confirm_libraries return data.frame object", {
  curdir  = getwd()
  tmpfile <- tempfile()
  dir.create(tmpfile)
  file.copy(file.path(curdir,"with_libraries.R"), file.path(tmpfile, "with_libraries.R"))
  setwd(tmpfile)
  capture.output(testdf <- confirm_libraries())
  expect_is(testdf,"data.frame")
  expect_equal(nrow(testdf),4)
  expect_equal(testdf$libraries,c("utils","base","stats",'DO_NOT_EXISTS'))
  expect_equal(testdf$installed,c("installed", "installed","installed","MISSING"))
  setwd(curdir)
})
